# Generated by Django 6.0.1 on 2026-02-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='aliases',
            field=models.CharField(blank=True, help_text='Дополнительные имена для поиска, через запятую', max_length=500, null=True),
        ),
    ]
