# Generated by Django 6.0.1 on 2026-02-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('m', 'метр'), ('pcs', 'штука')], default='pcs', max_length=10),
        ),
    ]
