# Generated by Django 6.0.1 on 2026-04-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('m', 'метр'), ('pcs', 'штука')], default='m', max_length=10),
        ),
    ]
